# Generated by Django 4.2.16 on 2024-10-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('host', models.CharField(max_length=200)),
                ('click_date', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorturl.shorturl')),
            ],
        ),
    ]
